from pathlib import Path
import sqlite3

from fastapi import FastAPI
from pydantic import BaseModel, Field, field_validator

from app.sql_validator import validate_sql
from app.llm.gemini import GeminiLLM
from app.services.schema_service import SchemaService
from app.services.query_services import QueryService


app = FastAPI()
llm = GeminiLLM()
schema_service = SchemaService()
query_service = QueryService(llm, schema_service)

# REQUEST MODEL

class QuestionRequest(BaseModel):
    question: str

    @field_validator("question")
    @classmethod
    def validate_question(cls, value):
        if not value.strip():
            raise ValueError("Question cannot be empty")

        return value.strip()

# RESPONSE MODEL

class QueryResponse(BaseModel):
    question: str
    generated_sql: str | None = None
    rows: list[dict] = Field(default_factory=list)
    answer: str | None = None
    error: str | None = None

# HOME

@app.get("/")
def home():
    return {
        "message": "AskDB backend is running"
    }

BASE_DIR = Path(__file__).resolve().parent.parent

DB_PATH = BASE_DIR / "database" / "company.db"

# DATABASE CONNECTION


def get_database_connection():
    connection = sqlite3.connect(str(DB_PATH))
    connection.row_factory = sqlite3.Row
    return connection

# DATABASE TEST

@app.get("/database-test")
def database_test():
    connection = get_database_connection()

    try:
        tables = connection.execute(
            """
            SELECT name
            FROM sqlite_master
            WHERE type = 'table'
            """
        ).fetchall()

        return {
            "tables": [table["name"] for table in tables]
        }

    finally:
        connection.close()


# EMPLOYEES TEST


@app.get("/employees-test")
def employees_test():
    connection = get_database_connection()

    try:
        employees = connection.execute(
            """
            SELECT
                employee_id,
                first_name,
                last_name,
                department,
                designation,
                salary,
                experience,
                city,
                state,
                employment_type,
                work_location,
                status
            FROM employees
            LIMIT 5
            """
        ).fetchall()

        return {
            "employees": [dict(employee) for employee in employees]
        }

    finally:
        connection.close()


# EXECUTE SQL

def execute_sql(sql: str):
    is_valid, message = validate_sql(sql)

    if not is_valid:
        return {
            "rows": [],
            "error": message
        }

    connection = get_database_connection()

    try:
        rows = connection.execute(sql).fetchall()

        return {
            "rows": [dict(row) for row in rows],
            "error": None
        }

    except sqlite3.Error as error:
        return {
            "rows": [],
            "error": f"SQL execution failed: {error}"
        }

    finally:
        connection.close()


# PROCESS QUESTION

def process_question(question: str):
    # Temporary SQL query.
    # Later, this will be generated by the LLM.

    test_sql = """
        SELECT
            employee_id,
            first_name,
            last_name,
            department,
            salary
        FROM employees
        LIMIT 5
    """

    result = execute_sql(test_sql)

    return {
        "generated_sql": test_sql.strip(),
        "rows": result["rows"],
        "error": result["error"]
    }


# ASK DATABASE

@app.post("/ask", response_model=QueryResponse)
def ask_database(request: QuestionRequest):
    result = process_question(request.question)

    if result["error"]:
        return {
            "question": request.question,
            "generated_sql": result["generated_sql"],
            "rows": [],
            "answer": None,
            "error": result["error"]
        }

    return {
        "question": request.question,
        "generated_sql": result["generated_sql"],
        "rows": result["rows"],
        "answer": (
            f"Query executed successfully. "
            f"{len(result['rows'])} rows returned."
        ),
        "error": None
    }
